<a href="https://colab.research.google.com/github/neeklaus09/pandas-practice/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

data ={'Name':['Alice','Bob','Charlie'],
      'Age':[25,30,35]}

In [12]:
df = pd.DataFrame(data)
print("DataFrame:\n",df)

DataFrame:
       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [14]:
df=pd.read_csv("student.csv")
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [15]:
df=pd.read_excel("student.xlsx")
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob   Five    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [16]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df['name']

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26       Big Nose
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [17]:
df['city']="Mumbai" ## no city name column

In [19]:
df

    id         name  class  mark  gender    city
0    1     John Deo   Four    75  female  Mumbai
1    2     Max Ruin  Three    85    male  Mumbai
2    3       Arnold  Three    55    male  Mumbai
3    4   Krish Star   Four    60  female  Mumbai
4    5    John Mike   Four    60  female  Mumbai
5    6    Alex John   Four    55    male  Mumbai
6    7  My John Rob   Five    78    male  Mumbai
7    8       Asruid   Five    85    male  Mumbai
8    9      Tes Qry    Six    78    male  Mumbai
9   10     Big John   Four    55  female  Mumbai
10  11       Ronald    Six    89  female  Mumbai
11  12        Recky    Six    94  female  Mumbai
12  13          Kty  Seven    88  female  Mumbai
13  14         Bigy  Seven    88  female  Mumbai
14  15     Tade Row   Four    88    male  Mumbai
15  16        Gimmy   Four    88    male  Mumbai
16  17        Tumyu    Six    54    male  Mumbai
17  18        Honny   Five    75    male  Mumbai
18  19        Tinny   Nine    18    male  Mumbai
19  20       Jackly   Nine    65  female  Mumbai
20  21   Babby John   Four    69  female  Mumbai
21  22       Reggid  Seven    55  female  Mumbai
22  23        Herod  Eight    79    male  Mumbai
23  24    Tiddy Now  Seven    78    male  Mumbai
24  25     Giff Tow    Six    88    male  Mumbai
25  26       Crelea  Seven    79    male  Mumbai
26  27     Big Nose  Three    81  female  Mumbai
27  28    Rojj Base  Seven    86  female  Mumbai
28  29  Tess Played  Seven    55    male  Mumbai
29  30    Reppy Red    Six    79  female  Mumbai
30  31  Marry Toeey   Four    88    male  Mumbai
31  32    Binn Rott  Seven    90  female  Mumbai
32  33    Kenn Rein    Six    96  female  Mumbai
33  34     Gain Toe  Seven    69    male  Mumbai
34  35   Rows Noump    Six    88  female  Mumbai

In [20]:
df['country']="India"

In [21]:
df

    id         name  class  mark  gender    city country
0    1     John Deo   Four    75  female  Mumbai   India
1    2     Max Ruin  Three    85    male  Mumbai   India
2    3       Arnold  Three    55    male  Mumbai   India
3    4   Krish Star   Four    60  female  Mumbai   India
4    5    John Mike   Four    60  female  Mumbai   India
5    6    Alex John   Four    55    male  Mumbai   India
6    7  My John Rob   Five    78    male  Mumbai   India
7    8       Asruid   Five    85    male  Mumbai   India
8    9      Tes Qry    Six    78    male  Mumbai   India
9   10     Big John   Four    55  female  Mumbai   India
10  11       Ronald    Six    89  female  Mumbai   India
11  12        Recky    Six    94  female  Mumbai   India
12  13          Kty  Seven    88  female  Mumbai   India
13  14         Bigy  Seven    88  female  Mumbai   India
14  15     Tade Row   Four    88    male  Mumbai   India
15  16        Gimmy   Four    88    male  Mumbai   India
16  17        Tumyu    Six    54    male  Mumbai   India
17  18        Honny   Five    75    male  Mumbai   India
18  19        Tinny   Nine    18    male  Mumbai   India
19  20       Jackly   Nine    65  female  Mumbai   India
20  21   Babby John   Four    69  female  Mumbai   India
21  22       Reggid  Seven    55  female  Mumbai   India
22  23        Herod  Eight    79    male  Mumbai   India
23  24    Tiddy Now  Seven    78    male  Mumbai   India
24  25     Giff Tow    Six    88    male  Mumbai   India
25  26       Crelea  Seven    79    male  Mumbai   India
26  27     Big Nose  Three    81  female  Mumbai   India
27  28    Rojj Base  Seven    86  female  Mumbai   India
28  29  Tess Played  Seven    55    male  Mumbai   India
29  30    Reppy Red    Six    79  female  Mumbai   India
30  31  Marry Toeey   Four    88    male  Mumbai   India
31  32    Binn Rott  Seven    90  female  Mumbai   India
32  33    Kenn Rein    Six    96  female  Mumbai   India
33  34     Gain Toe  Seven    69    male  Mumbai   India
34  35   Rows Noump    Six    88  female  Mumbai   India

In [22]:
df=df.drop('city',axis=1)
df

    id         name  class  mark  gender country
0    1     John Deo   Four    75  female   India
1    2     Max Ruin  Three    85    male   India
2    3       Arnold  Three    55    male   India
3    4   Krish Star   Four    60  female   India
4    5    John Mike   Four    60  female   India
5    6    Alex John   Four    55    male   India
6    7  My John Rob   Five    78    male   India
7    8       Asruid   Five    85    male   India
8    9      Tes Qry    Six    78    male   India
9   10     Big John   Four    55  female   India
10  11       Ronald    Six    89  female   India
11  12        Recky    Six    94  female   India
12  13          Kty  Seven    88  female   India
13  14         Bigy  Seven    88  female   India
14  15     Tade Row   Four    88    male   India
15  16        Gimmy   Four    88    male   India
16  17        Tumyu    Six    54    male   India
17  18        Honny   Five    75    male   India
18  19        Tinny   Nine    18    male   India
19  20       Jackly   Nine    65  female   India
20  21   Babby John   Four    69  female   India
21  22       Reggid  Seven    55  female   India
22  23        Herod  Eight    79    male   India
23  24    Tiddy Now  Seven    78    male   India
24  25     Giff Tow    Six    88    male   India
25  26       Crelea  Seven    79    male   India
26  27     Big Nose  Three    81  female   India
27  28    Rojj Base  Seven    86  female   India
28  29  Tess Played  Seven    55    male   India
29  30    Reppy Red    Six    79  female   India
30  31  Marry Toeey   Four    88    male   India
31  32    Binn Rott  Seven    90  female   India
32  33    Kenn Rein    Six    96  female   India
33  34     Gain Toe  Seven    69    male   India
34  35   Rows Noump    Six    88  female   India

In [23]:
del df['country']
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob   Five    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.describe()

In [26]:
df['mark'].mean()

np.float64(74.65714285714286)

In [25]:
df['mark'].mode()

0    88
Name: mark, dtype: int64

In [24]:
#counting the occurences of each value in the 'mark' column
mark_counts=df['mark'].value_counts()
mark_counts

mark
88    7
55    5
78    3
79    3
75    2
60    2
85    2
69    2
89    1
54    1
94    1
65    1
18    1
81    1
86    1
90    1
96    1
Name: count, dtype: int64

lecture 5th

In [27]:
df.loc[:,:]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob   Five    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [28]:
df.iloc[:,:]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob   Five    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [29]:
df.loc[0:4:2,:]

   id       name  class  mark  gender
0   1   John Deo   Four    75  female
2   3     Arnold  Three    55    male
4   5  John Mike   Four    60  female

In [30]:
df.iloc[0:4:1,:]

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female

In [31]:
df.loc[0:4,'name':'mark']

         name  class  mark
0    John Deo   Four    75
1    Max Ruin  Three    85
2      Arnold  Three    55
3  Krish Star   Four    60
4   John Mike   Four    60

In [32]:
df.iloc[0:5,1:4]

         name  class  mark
0    John Deo   Four    75
1    Max Ruin  Three    85
2      Arnold  Three    55
3  Krish Star   Four    60
4   John Mike   Four    60

In [33]:
df[df['mark']>90]

    id       name class  mark  gender
11  12      Recky   Six    94  female
32  33  Kenn Rein   Six    96  female

In [34]:
df.iloc[[3,7,11,27],[1,4]]

          name  gender
3   Krish Star  female
7       Asruid    male
11       Recky  female
27   Rojj Base  female

In [35]:
df.iloc[:,::2]

    id  class  gender
0    1   Four  female
1    2  Three    male
2    3  Three    male
3    4   Four  female
4    5   Four  female
5    6   Four    male
6    7   Five    male
7    8   Five    male
8    9    Six    male
9   10   Four  female
10  11    Six  female
11  12    Six  female
12  13  Seven  female
13  14  Seven  female
14  15   Four    male
15  16   Four    male
16  17    Six    male
17  18   Five    male
18  19   Nine    male
19  20   Nine  female
20  21   Four  female
21  22  Seven  female
22  23  Eight    male
23  24  Seven    male
24  25    Six    male
25  26  Seven    male
26  27  Three  female
27  28  Seven  female
28  29  Seven    male
29  30    Six  female
30  31   Four    male
31  32  Seven  female
32  33    Six  female
33  34  Seven    male
34  35    Six  female

In [36]:
df.loc[::2,::2]

    id  class  gender
0    1   Four  female
2    3  Three    male
4    5   Four  female
6    7   Five    male
8    9    Six    male
10  11    Six  female
12  13  Seven  female
14  15   Four    male
16  17    Six    male
18  19   Nine    male
20  21   Four  female
22  23  Eight    male
24  25    Six    male
26  27  Three  female
28  29  Seven    male
30  31   Four    male
32  33    Six  female
34  35    Six  female

lect *9* leetcode 6th and 7th

In [37]:
import pandas as pd

In [38]:
df=pd.read_excel("Data.xlsx",sheet_name='Problem 6')
df

   customer_id      name                email
0          101    Sophia   sophia@example.com
1          102      Liam   olivia@example.com
2          103     Ethan     noah@example.com
3          104       Ava  william@example.com
4          105       Mia     emma@example.com
5          106      Noah     liam@example.com
6          107     James      ava@example.com
7          108  Isabella   sophia@example.com

In [40]:
cleaned_customers=df.drop_duplicates(subset=['email'],keep='first')

In [41]:
cleaned_customers

   customer_id    name                email
0          101  Sophia   sophia@example.com
1          102    Liam   olivia@example.com
2          103   Ethan     noah@example.com
3          104     Ava  william@example.com
4          105     Mia     emma@example.com
5          106    Noah     liam@example.com
6          107   James      ava@example.com

In [43]:
df1=pd.read_excel("Data.xlsx",sheet_name='Problem 7')
df1

   student_id     name  age
0         101    Alice   18
1         202      Bob   20
2         303      NaN   22
3         404  Charlie   19

In [47]:
df1.dropna(subset=['name'],inplace=True)

In [48]:
df1

   student_id     name  age
0         101    Alice   18
1         202      Bob   20
3         404  Charlie   19

lecture 9th p-8,9

In [ ]:
import pandas as pd

In [49]:
df=pd.read_excel("Data.xlsx",sheet_name='Problem 8')
df

  Product_name  Price
0        Apple     50
1       Banana     30
2       Orange     70
3        Mango     40

In [50]:
df['Price']=df['Price']*2
df

  Product_name  Price
0        Apple    100
1       Banana     60
2       Orange    140
3        Mango     80

In [54]:
df9=pd.read_excel("Data.xlsx",sheet_name='Problem 9')
df9

   emp_id    first      last  years_exp
0     101     John       Doe          5
1     102     Jane     Smith         10
2     103    Emily   Johnson          3
3     104  Michael  Williams          8

In [56]:
df9=df9.rename(columns={
  'emp_id':'employee_id',
  'first':'first_name',
  'last':'last_name',
  'years_exp':'experience_years'
})
df9

   employee_id first_name last_name  experience_years
0          101       John       Doe                 5
1          102       Jane     Smith                10
2          103      Emily   Johnson                 3
3          104    Michael  Williams                 8

In [58]:
df9.columns=['emp_id_new',"first_new","last_new",'exp_new']
df9

   emp_id_new first_new  last_new  exp_new
0         101      John       Doe        5
1         102      Jane     Smith       10
2         103     Emily   Johnson        3
3         104   Michael  Williams        8

lecture 11 : problem 10 & problem 11

p-10: changing the datatype

In [65]:
df10=pd.read_excel("Data.xlsx",sheet_name="Problem 10",dtype={
    'employee_id':int,
    'name':str,
    'department':str,
    'salary':float ##explicityly mentionioning the data type to change
})
df10

   employee_id     name department   salary
0          101     John         HR  55000.0
1          102     Emma    Finance  62000.0
2          103  Michael         IT  72000.0

In [66]:
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  3 non-null      int64
 1   name         3 non-null      object
 2   department   3 non-null      object
 3   salary       3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 228.0+ bytes

In [67]:
#converting salary to int
df10['salary']=df10['salary'].astype(int)

In [68]:
df10

   employee_id     name department  salary
0          101     John         HR   55000
1          102     Emma    Finance   62000
2          103  Michael         IT   72000

In [69]:
df11=pd.read_excel("Data.xlsx",sheet_name='Problem 11')
df11

  product_name  quantity_ordered  total_price
0       Laptop               NaN         1500
1       Tablet               NaN          500
2   Smartphone              25.0         1000
3       Camera              10.0          800

p-11 replacing na with 0

In [ ]:
df11['quantity_ordered'].fillna(0,inplace=True)

lect 12 : p 12 and p 13

p12: reshaping data :concatenate

In [72]:
df112=pd.read_excel("Data.xlsx",sheet_name='df1 Problem 12')
df112

   order_id product  quantity
0       101   Apple         5
1       102  Banana         3
2       103    Kiwi         2

In [73]:
df212=pd.read_excel("Data.xlsx",sheet_name='df2 Problem 12')
df212

   order_id product  quantity
0       201  Orange        10
1       202  Papaya         7
2       203   Mango         8

In [77]:
result=pd.concat([df112,df212],axis=0)
result

   order_id product  quantity
0       101   Apple         5
1       102  Banana         3
2       103    Kiwi         2
0       201  Orange        10
1       202  Papaya         7
2       203   Mango         8

In [78]:

resultt=pd.concat([df112,df212],axis=1)
resultt

   order_id product  quantity  order_id product  quantity
0       101   Apple         5       201  Orange        10
1       102  Banana         3       202  Papaya         7
2       103    Kiwi         2       203   Mango         8

p:13 -pivoting

In [79]:
df13=pd.read_excel("Data.xlsx",sheet_name='Problem 13')
df13

  Product Quarter  Revenue
0  Orange      Q1     5000
1  Orange      Q2     7000
2  Orange      Q3     8000
3  Orange      Q4     6000
4   Apple      Q1     3000
5   Apple      Q2     5000
6   Apple      Q3     4000
7   Apple      Q4     7000

In [82]:
pivoted_df= df13.pivot(index='Quarter',columns='Product',values='Revenue')
pivoted_df

Product  Apple  Orange
Quarter
Q1        3000    5000
Q2        5000    7000
Q3        4000    8000
Q4        7000    6000

In [83]:
pivoted_df= df13.pivot_table(index='Quarter',columns='Product',values='Revenue')
pivoted_df

Product   Apple  Orange
Quarter
Q1       3000.0  5000.0
Q2       5000.0  7000.0
Q3       4000.0  8000.0
Q4       7000.0  6000.0

lec 13: p 14,15

p-14 reshaping melt

In [ ]:
p-15 method chaining

In [84]:
df15=pd.read_excel("Data.xlsx",sheet_name='Problem 15')
df15

   student_id   name subject   score
0           1  Alice     Math     91
1           2    Bob  Science     88
2           3  Carol  English     92
3           4  David     Math     85
4           5  Emily  Science     95

In [86]:
temp1=df15[df15['score']>90]
temp1

   student_id   name subject   score
0           1  Alice     Math     91
2           3  Carol  English     92
4           5  Emily  Science     95

In [87]:
temp2=temp1.sort_values('score',ascending=False)
temp2

   student_id   name subject   score
4           5  Emily  Science     95
2           3  Carol  English     92
0           1  Alice     Math     91

In [88]:
temp2['name']

4    Emily
2    Carol
0    Alice
Name: name, dtype: object

In [93]:
output=df15[df15['score']>90].sort_values('score',ascending=False)['name']

In [94]:
output

4    Emily
2    Carol
0    Alice
Name: name, dtype: object